# Step 4 ML

In [7]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

In [2]:
df_test = pd.read_csv("test_extracted_features_step_3.csv") # 46435
df_train= pd.read_csv("train_extracted_features_step_3.csv") # 254983

df_test = df_test.drop('sentence', axis= 1)
df_test.fillna(0, inplace=True)
            
df_train = df_train.drop('sentence', axis= 1)
df_train.fillna(0, inplace=True)

In [3]:
df_train

,word,pos_tag,chunk_tag,lemmas,hypernyms,hyponyms,holonyms,meronyms,target
0,eu,NNP,B-NP,eu,metal world_organisation world_organization in...,0,0,0,3
1,rejects,VBZ,B-VP,reject,refuse evaluate react decline judge deciding d...,brush_aside recuse disregard snub object disco...,0,0,0
2,german,JJ,B-NP,german,West_Germanic_language European West_Germanic,Middle_High_German Prussian Hun Jerry Teuton K...,Deutschland Germany FRG Federal_Republic_of_Ge...,0,4
3,call,NN,I-NP,call,shelve read disposition wake inclination requi...,bellowing read clamoring supervisor_call_instr...,0,0,0
4,to,TO,B-VP,to,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
254978,.,.,O,.,0,0,0,0,0
254979,--,:,O,--,0,0,0,0,0
254980,dhaka,NNP,B-NP,dhaka,0,0,0,0,3
254981,newsroom,NNP,I-NP,newsroom,reading_room business_office office staff,0,0,0,3
254982,880-2-506363,CD,I-NP,880-2-506363,0,0,0,0,0

In [4]:
df_test

,word,pos_tag,chunk_tag,lemmas,hypernyms,hyponyms,holonyms,meronyms,target
0,soccer,NN,B-NP,soccer,football football_game,0,0,headshot,0
1,-,:,O,-,0,0,0,0,0
2,japan,NNP,B-NP,japan,lacquer lacquerware,0,0,Japanese_capital Yezo Yedo Toyota Mount_Asama ...,2
3,get,VB,B-VP,get,gravel sicken confound stir go_forth channelis...,realise get_cracking fledge come work_up preem...,0,0,0
4,lucky,NNP,B-NP,lucky,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
46430,younger,JJR,I-NP,younger,0,0,0,0,0
46431,brother,NN,I-NP,brother,monastic member monk male_sibling fellow_membe...,half-brother stepbrother little_brother Freema...,brotherhood sodality fraternity,0,0
46432,",",",",O,",",0,0,0,0,0
46433,bobby,NNP,B-NP,bobby,policeman police_officer officer,0,0,0,1
46434,.,.,O,.,0,0,0,0,0

In [5]:
df = pd.concat([df_train, df_test], ignore_index=True) # 301418
df

,word,pos_tag,chunk_tag,lemmas,hypernyms,hyponyms,holonyms,meronyms,target
0,eu,NNP,B-NP,eu,metal world_organisation world_organization in...,0,0,0,3
1,rejects,VBZ,B-VP,reject,refuse evaluate react decline judge deciding d...,brush_aside recuse disregard snub object disco...,0,0,0
2,german,JJ,B-NP,german,West_Germanic_language European West_Germanic,Middle_High_German Prussian Hun Jerry Teuton K...,Deutschland Germany FRG Federal_Republic_of_Ge...,0,4
3,call,NN,I-NP,call,shelve read disposition wake inclination requi...,bellowing read clamoring supervisor_call_instr...,0,0,0
4,to,TO,B-VP,to,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
301413,younger,JJR,I-NP,younger,0,0,0,0,0
301414,brother,NN,I-NP,brother,monastic member monk male_sibling fellow_membe...,half-brother stepbrother little_brother Freema...,brotherhood sodality fraternity,0,0
301415,",",",",O,",",0,0,0,0,0
301416,bobby,NNP,B-NP,bobby,policeman police_officer officer,0,0,0,1
301417,.,.,O,.,0,0,0,0,0

In [8]:
x = df.drop('target', axis=1)
v = DictVectorizer(sparse=True)
x = v.fit_transform(x.to_dict('records'))
y = df['target'].values
classes = np.unique(y)
classes = classes.tolist()
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state=0)
x_train.shape, x_test.shape

((201950, 71709), (99468, 71709))

In [9]:
clf = LogisticRegression(random_state=0, solver='lbfgs',
                         multi_class= 'multinomial').fit(x_train, y_train)

y_pre= clf.predict(x_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)

In [12]:
target_names = ['class O', 'class B|I-PER ', 'class B|I-LOC','class B|I-ORG', 'class B|I-MISC']
print(classification_report(y_test, y_pre, target_names=target_names))

                precision    recall  f1-score   support

       class O       0.99      0.99      0.99     82664
class B|I-PER        0.81      0.94      0.87      5614
 class B|I-LOC       0.86      0.80      0.83      4026
 class B|I-ORG       0.84      0.70      0.76      4882
class B|I-MISC       0.90      0.71      0.79      2282

      accuracy                           0.96     99468
     macro avg       0.88      0.83      0.85     99468
  weighted avg       0.96      0.96      0.96     99468